export * from './Test/Test'
export * from './Header/Header'
export * from './Footer/Footer'
export * from './Home/Home'
export * from './Categories/Categories'
export * from './Favorites/Favorites'
export * from './Cart/Cart'
export * from './Orders/Orders'