name: Publish Docker

on:
  push:
    branches: [main]

jobs:
  create-envfile:
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL}}
          envkey_APP_STATIC_CONTENT_URL: ${{secrets.REACT_APP_STATIC_CONTENT_URL}}
          directory: "./"
          file_name: ".env.local"
          fail_on_empty: true

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/vlad-tikhonov/ts-react-redux-eshop/eshop-front
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "develop"
